


2021-10-10-15:44:50    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:44:50    INFO: Calling: __init__...
2021-10-10-15:44:50    INFO: Calling: create_directory...
2021-10-10-15:44:50    INFO: Calling: load_data...
2021-10-10-15:44:53    INFO: Calling: setup_model...
2021-10-10-15:44:53    INFO: Calling: setup_model...
2021-10-10-15:44:53    INFO: Calling: load_checkpoint...
2021-10-10-15:44:55    INFO: Calling: generate_figs...
2021-10-10-15:45:04    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 98, in generate_figs
    reconstruction, (objects, object_ids, protos) = self.model(imgs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 299, in forward
    objects, masks, object_ids = self._greedy_selection(
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 165, in _greedy_selection
    masks=torch.cat([aux_masks_, masks_temps], dim=1),
RuntimeError: CUDA out of memory. Tried to allocate 5.19 GiB (GPU 0; 23.70 GiB total capacity; 16.50 GiB already allocated; 5.04 GiB free; 17.25 GiB reserved in total by PyTorch)




2021-10-10-15:45:31    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:45:31    INFO: Calling: __init__...
2021-10-10-15:45:31    INFO: Calling: create_directory...
2021-10-10-15:45:31    INFO: Calling: load_data...
2021-10-10-15:45:35    INFO: Calling: setup_model...
2021-10-10-15:45:35    INFO: Calling: setup_model...
2021-10-10-15:45:35    INFO: Calling: load_checkpoint...
2021-10-10-15:45:37    INFO: Calling: generate_figs...
2021-10-10-15:45:45    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 98, in generate_figs
    reconstruction, (objects, object_ids, protos) = self.model(imgs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 299, in forward
    objects, masks, object_ids = self._greedy_selection(
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 165, in _greedy_selection
    masks=torch.cat([aux_masks_, masks_temps], dim=1),
RuntimeError: CUDA out of memory. Tried to allocate 5.19 GiB (GPU 0; 23.70 GiB total capacity; 16.50 GiB already allocated; 5.04 GiB free; 17.25 GiB reserved in total by PyTorch)




2021-10-10-15:51:54    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:51:54    INFO: Calling: __init__...
2021-10-10-15:51:54    INFO: Calling: create_directory...
2021-10-10-15:51:54    INFO: Calling: load_data...
2021-10-10-15:51:55    INFO: Calling: setup_model...
2021-10-10-15:51:55    INFO: Calling: setup_model...
2021-10-10-15:51:55    INFO: Calling: load_checkpoint...
2021-10-10-15:51:56    INFO: Calling: generate_figs...
2021-10-10-15:52:05    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 98, in generate_figs
    reconstruction, (objects, object_ids, protos) = self.model(imgs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 299, in forward
    objects, masks, object_ids = self._greedy_selection(
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 165, in _greedy_selection
    masks=torch.cat([aux_masks_, masks_temps], dim=1),
RuntimeError: CUDA out of memory. Tried to allocate 5.19 GiB (GPU 0; 23.70 GiB total capacity; 16.50 GiB already allocated; 5.04 GiB free; 17.25 GiB reserved in total by PyTorch)




2021-10-10-15:53:02    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:53:02    INFO: Calling: __init__...
2021-10-10-15:53:02    INFO: Calling: create_directory...
2021-10-10-15:53:02    INFO: Calling: load_data...
2021-10-10-15:53:02    INFO: Calling: setup_model...
2021-10-10-15:53:02    INFO: Calling: setup_model...
2021-10-10-15:53:02    INFO: Calling: load_checkpoint...
2021-10-10-15:53:04    INFO: Calling: generate_figs...



2021-10-10-15:54:30    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:54:30    INFO: Calling: __init__...
2021-10-10-15:54:30    INFO: Calling: create_directory...
2021-10-10-15:54:30    INFO: Calling: load_data...
2021-10-10-15:54:31    INFO: Calling: setup_model...
2021-10-10-15:54:31    INFO: Calling: setup_model...
2021-10-10-15:54:31    INFO: Calling: load_checkpoint...
2021-10-10-15:54:32    INFO: Calling: generate_figs...
2021-10-10-15:54:41    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 98, in generate_figs
    reconstruction, (objects, object_ids, protos) = self.model(imgs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 299, in forward
    objects, masks, object_ids = self._greedy_selection(
  File "/home/user/villar/PCDNet/src/models/PrototypicalDissentangler.py", line 165, in _greedy_selection
    masks=torch.cat([aux_masks_, masks_temps], dim=1),
RuntimeError: CUDA out of memory. Tried to allocate 5.19 GiB (GPU 0; 23.70 GiB total capacity; 16.50 GiB already allocated; 5.04 GiB free; 17.25 GiB reserved in total by PyTorch)




2021-10-10-15:55:18    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:55:18    INFO: Calling: __init__...
2021-10-10-15:55:18    INFO: Calling: create_directory...
2021-10-10-15:55:18    INFO: Calling: load_data...
2021-10-10-15:55:18    INFO: Calling: setup_model...
2021-10-10-15:55:18    INFO: Calling: setup_model...
2021-10-10-15:55:18    INFO: Calling: load_checkpoint...
2021-10-10-15:55:20    INFO: Calling: generate_figs...
2021-10-10-15:55:20    INFO: Calling: create_directory...
2021-10-10-15:55:22    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 142, in generate_figs
    bin_mask = self.model.process_masks(self.model.final_masks, thr=THR[self.dataset_name])
KeyError: 'AtariSpace'




2021-10-10-15:55:57    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:55:57    INFO: Calling: __init__...
2021-10-10-15:55:57    INFO: Calling: create_directory...
2021-10-10-15:55:57    INFO: Calling: load_data...
2021-10-10-15:55:57    INFO: Calling: setup_model...
2021-10-10-15:55:57    INFO: Calling: setup_model...
2021-10-10-15:55:57    INFO: Calling: load_checkpoint...



2021-10-10-15:56:03    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:56:03    INFO: Calling: __init__...
2021-10-10-15:56:03    INFO: Calling: create_directory...
2021-10-10-15:56:03    INFO: Calling: load_data...
2021-10-10-15:56:03    INFO: Calling: setup_model...
2021-10-10-15:56:03    INFO: Calling: setup_model...
2021-10-10-15:56:03    INFO: Calling: load_checkpoint...
2021-10-10-15:56:05    INFO: Calling: generate_figs...
2021-10-10-15:56:06    INFO: Calling: create_directory...
2021-10-10-15:56:09    INFO: Calling: generate_figs...
2021-10-10-15:56:09    INFO: Calling: create_directory...
2021-10-10-15:56:12    INFO: Calling: generate_figs...
2021-10-10-15:56:13    INFO: Calling: create_directory...
2021-10-10-15:56:16    INFO: Calling: generate_figs...
2021-10-10-15:56:16    INFO: Calling: create_directory...
2021-10-10-15:56:20    INFO: Calling: generate_figs...
2021-10-10-15:56:20    INFO: Calling: create_directory...
2021-10-10-15:56:23    INFO: Calling: generate_global_figs...



2021-10-10-15:58:38    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:58:38    INFO: Calling: __init__...
2021-10-10-15:58:38    INFO: Calling: create_directory...
2021-10-10-15:58:38    INFO: Calling: load_data...
2021-10-10-15:58:39    INFO: Calling: setup_model...
2021-10-10-15:58:39    INFO: Calling: setup_model...
2021-10-10-15:58:39    INFO: Calling: load_checkpoint...
2021-10-10-15:58:40    INFO: Calling: generate_figs...
2021-10-10-15:58:41    INFO: Calling: create_directory...
2021-10-10-15:58:43    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 143, in generate_figs
    bin_mask = self.model.templates * bin_mask
RuntimeError: The size of tensor a (120) must match the size of tensor b (50) at non-singleton dimension 1




2021-10-10-15:59:02    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:59:02    INFO: Calling: __init__...
2021-10-10-15:59:02    INFO: Calling: create_directory...
2021-10-10-15:59:02    INFO: Calling: load_data...
2021-10-10-15:59:03    INFO: Calling: setup_model...
2021-10-10-15:59:03    INFO: Calling: setup_model...
2021-10-10-15:59:03    INFO: Calling: load_checkpoint...
2021-10-10-15:59:04    INFO: Calling: generate_figs...
2021-10-10-15:59:05    INFO: Calling: create_directory...
2021-10-10-15:59:07    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 145, in generate_figs
    bin_mask = self.model.templates * bin_mask
RuntimeError: The size of tensor a (120) must match the size of tensor b (50) at non-singleton dimension 1




2021-10-10-15:59:32    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:59:32    INFO: Calling: __init__...
2021-10-10-15:59:32    INFO: Calling: create_directory...
2021-10-10-15:59:32    INFO: Calling: load_data...
2021-10-10-15:59:33    INFO: Calling: setup_model...
2021-10-10-15:59:33    INFO: Calling: setup_model...
2021-10-10-15:59:33    INFO: Calling: load_checkpoint...
2021-10-10-15:59:34    INFO: Calling: generate_figs...
2021-10-10-15:59:35    INFO: Calling: create_directory...
2021-10-10-15:59:37    ERROR: Traceback (most recent call last):
  File "/home/user/villar/PCDNet/src/lib/logger.py", line 24, in try_call_log
    return func(*args, **kwargs)
  File "/home/user/villar/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "04_generate_figures.py", line 145, in generate_figs
    bin_mask = self.model.templates * bin_mask
RuntimeError: The size of tensor a (120) must match the size of tensor b (50) at non-singleton dimension 1




2021-10-10-15:59:54    NEW_EXP: Starting Figure generation procedure
2021-10-10-15:59:54    INFO: Calling: __init__...
2021-10-10-15:59:54    INFO: Calling: create_directory...
2021-10-10-15:59:54    INFO: Calling: load_data...
2021-10-10-15:59:54    INFO: Calling: setup_model...
2021-10-10-15:59:54    INFO: Calling: setup_model...
2021-10-10-15:59:54    INFO: Calling: load_checkpoint...
2021-10-10-15:59:56    INFO: Calling: generate_figs...
2021-10-10-15:59:57    INFO: Calling: create_directory...
2021-10-10-16:00:00    INFO: Calling: generate_figs...
2021-10-10-16:00:00    INFO: Calling: create_directory...
2021-10-10-16:00:03    INFO: Calling: generate_figs...
2021-10-10-16:00:04    INFO: Calling: create_directory...
2021-10-10-16:00:07    INFO: Calling: generate_figs...
2021-10-10-16:00:07    INFO: Calling: create_directory...
2021-10-10-16:00:10    INFO: Calling: generate_figs...
2021-10-10-16:00:11    INFO: Calling: create_directory...
2021-10-10-16:00:14    INFO: Calling: generate_global_figs...



2021-10-10-16:04:13    NEW_EXP: Starting Figure generation procedure
2021-10-10-16:04:13    INFO: Calling: __init__...
2021-10-10-16:04:13    INFO: Calling: create_directory...
2021-10-10-16:04:13    INFO: Calling: load_data...
2021-10-10-16:04:13    INFO: Calling: setup_model...
2021-10-10-16:04:13    INFO: Calling: setup_model...
2021-10-10-16:04:13    INFO: Calling: load_checkpoint...
2021-10-10-16:04:15    INFO: Calling: generate_figs...
2021-10-10-16:04:16    INFO: Calling: create_directory...
2021-10-10-16:04:19    INFO: Calling: generate_figs...
2021-10-10-16:04:19    INFO: Calling: create_directory...
2021-10-10-16:04:23    INFO: Calling: generate_figs...
2021-10-10-16:04:23    INFO: Calling: create_directory...
2021-10-10-16:04:26    INFO: Calling: generate_figs...
2021-10-10-16:04:27    INFO: Calling: create_directory...
2021-10-10-16:04:30    INFO: Calling: generate_figs...
2021-10-10-16:04:30    INFO: Calling: create_directory...
2021-10-10-16:04:34    INFO: Calling: generate_global_figs...



2021-10-10-16:55:03    NEW_EXP: Starting Figure generation procedure
2021-10-10-16:55:03    INFO: Calling: __init__...
2021-10-10-16:55:03    INFO: Calling: create_directory...
2021-10-10-16:55:03    INFO: Calling: load_data...
2021-10-10-16:55:04    INFO: Calling: setup_model...
2021-10-10-16:55:04    INFO: Calling: setup_model...
2021-10-10-16:55:04    INFO: Calling: load_checkpoint...
2021-10-10-16:55:05    INFO: Calling: generate_figs...
2021-10-10-16:55:06    INFO: Calling: create_directory...
2021-10-10-16:55:09    INFO: Calling: generate_figs...
2021-10-10-16:55:10    INFO: Calling: create_directory...
2021-10-10-16:55:13    INFO: Calling: generate_figs...
2021-10-10-16:55:14    INFO: Calling: create_directory...
2021-10-10-16:55:17    INFO: Calling: generate_figs...
2021-10-10-16:55:17    INFO: Calling: create_directory...
2021-10-10-16:55:20    INFO: Calling: generate_figs...
2021-10-10-16:55:21    INFO: Calling: create_directory...
2021-10-10-16:55:24    INFO: Calling: generate_global_figs...
